/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.dl.client.view;

import com.ijse.dl.client.controllerfactoryimpl.ControllerFactoryImpl;
import com.ijse.dl.client.view.util.Validation;
import com.ijse.dl.common.dto.Membership;
import com.ijse.dl.common.dto.User;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Randula
 */
public class AdminSignUp extends javax.swing.JDialog {

    private Icon icon = new ImageIcon(getClass().getResource(
            "/com/ijse/dl/client/view/images/block.png"));

    /**
     * Creates new form AdminSignUp
     *
     * @param parent
     * @param modal
     */
    public AdminSignUp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblNic = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        lblTelephone = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        lblNic1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pssPassword = new javax.swing.JPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        pssPassword1 = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        lblFinish = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 51, 204));
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 330, 36));

        lblName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Full Name");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 89, 24));

        lblNic.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNic.setForeground(new java.awt.Color(255, 255, 255));
        lblNic.setText("NIC Number");
        getContentPane().add(lblNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 89, 24));

        txtNic.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNic.setForeground(new java.awt.Color(0, 51, 204));
        txtNic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtNic.setOpaque(false);
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });
        getContentPane().add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, 36));

        lblTelephone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTelephone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelephone.setText("Telephone Number");
        getContentPane().add(lblTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 141, 24));

        txtTelephone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtTelephone.setForeground(new java.awt.Color(0, 51, 204));
        txtTelephone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtTelephone.setOpaque(false);
        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });
        txtTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneKeyReleased(evt);
            }
        });
        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 330, 36));

        lblEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 89, 24));

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 51, 204));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtEmail.setOpaque(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 330, 36));

        lblName1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Your User Id...");
        getContentPane().add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 116, 24));

        txtUserId.setEditable(false);
        txtUserId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(255, 102, 102));
        txtUserId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserId.setText("This Will Fill Automatically");
        txtUserId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtUserId.setOpaque(false);
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 330, 36));

        lblNic1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNic1.setForeground(new java.awt.Color(255, 255, 255));
        lblNic1.setText("User Name");
        getContentPane().add(lblNic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 89, 24));

        txtUserName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 51, 204));
        txtUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtUserName.setOpaque(false);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 330, 36));

        lblPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Set your Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 174, 24));

        pssPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pssPassword.setForeground(new java.awt.Color(0, 51, 204));
        pssPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pssPassword.setOpaque(false);
        pssPassword.setPreferredSize(new java.awt.Dimension(72, 23));
        getContentPane().add(pssPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 330, 36));

        lblPassword1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Re-enter Password");
        getContentPane().add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 177, 24));

        pssPassword1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pssPassword1.setForeground(new java.awt.Color(0, 51, 204));
        pssPassword1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pssPassword1.setOpaque(false);
        pssPassword1.setPreferredSize(new java.awt.Dimension(72, 23));
        getContentPane().add(pssPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 330, 36));

        lblError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 255, 255));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("We found error in your password!");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 200, 25));

        lblFinish.setBackground(new java.awt.Color(29, 78, 217));
        lblFinish.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblFinish.setForeground(new java.awt.Color(255, 255, 255));
        lblFinish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinish.setText("Finish");
        lblFinish.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblFinish.setOpaque(true);
        lblFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinishMouseClicked(evt);
            }
        });
        getContentPane().add(lblFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 96, 33));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 10, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        Validation.name(txtNic);

    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        Validation.textNewNIC(txtNic);
    }//GEN-LAST:event_txtNicKeyReleased

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneKeyReleased
        Validation.phoneNumber(txtTelephone, evt);
    }//GEN-LAST:event_txtTelephoneKeyReleased

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void lblFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinishMouseClicked
        String password = String.valueOf(pssPassword.getPassword());
        String passComf = String.valueOf(pssPassword1.getPassword());
        if (password.equals(passComf)) {
            try {
                String genId = saveUserAndMember();
                if (genId != null) {
                    txtUserId.setText(genId);
                    JOptionPane.showMessageDialog(this,
                            "Welcome to Maze | Digital Library..."
                            + "\n" + "Your User Id is : " + genId, "Message",
                            JOptionPane.PLAIN_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Sign Up Failed...", "Message",
                            JOptionPane.PLAIN_MESSAGE);
                }
            } catch (IOException ex) {
                System.err.println(ex.getMessage());
            } catch (NotBoundException ex) {
                JOptionPane.showMessageDialog(null, "Server Disconnected",
                        "Oops!",
                        JOptionPane.INFORMATION_MESSAGE, icon);
            }
        } else {
            lblError.setVisible(true);
            pssPassword.setText(null);
            pssPassword1.setText(null);
        }
    }//GEN-LAST:event_lblFinishMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminSignUp dialog
                        = new AdminSignUp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFinish;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblNic1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JPasswordField pssPassword;
    private javax.swing.JPasswordField pssPassword1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private String saveUserAndMember()
            throws IOException, RemoteException, NotBoundException {
        String name = txtName.getText();
        String nic = txtNic.getText();
        String telephone = txtTelephone.getText();
        String email = txtEmail.getText();

        String userName = txtUserName.getText();
        String password = String.valueOf(pssPassword.getPassword());
        String passComf = String.valueOf(pssPassword1.getPassword());

        Date date = new Date();
        SimpleDateFormat simpledateformat
                = (SimpleDateFormat) DateFormat
                .getDateInstance(DateFormat.LONG);
        String newDate = simpledateformat.format(date);

        User user
                = new User("0", name, nic,
                        telephone, email, "Admin");
        Membership membership
                = new Membership("0", userName,
                        password, newDate, "Admin");
        String genId
                = new ControllerFactoryImpl()
                .getMemberController().addAsMember(membership, user);

        return genId;
    }
}
