/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.dl.client.view;

import com.ijse.dl.client.controllerfactoryimpl.ControllerFactoryImpl;
import com.ijse.dl.common.dto.Log;
import com.ijse.dl.common.dto.Membership;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.rmi.NotBoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Randula
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    private CatalogForm catalogForm;    //Keep Catalog Form
    private RequestForm requestForm;     //Keep Request Form
    private HistoryFrame historyFrame;   //Keep History Form
    private AccountFrame accountFrame;   //Keep User Account Form
    private String userName;
    private String id;
    private Log log;
    private int posX;
    private int posY;
    private Icon icon = new ImageIcon(getClass().getResource(
            "/com/ijse/dl/client/view/images/block.png"));

    public HomeFrame(String id) {
        try {
            initComponents();
            setFullScreen();
            getTime();
            getDate();

            Membership membership = new ControllerFactoryImpl()
                    .getMemberController().searchMembership(id);
            this.userName = membership.getUserName();
            this.id = id;
            lblUserName.setText(userName);

            setLog();

        } catch (IOException | NotBoundException ex) {
            JOptionPane.showMessageDialog(null, "Server Disconnected", "Oops!",
                    JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }

    public String getId() {
        return id;
    }

    public String getUserName() {
        return userName;
    }

    public Log getLog() {
        return log;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblCatalog = new javax.swing.JLabel();
        lblRequest = new javax.swing.JLabel();
        lblHistory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1390, 770));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText("Time");
        getContentPane().add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 20));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/account1.png"))); // NOI18N
        lblAccount.setText("Account");
        lblAccount.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAccountMouseExited(evt);
            }
        });
        getContentPane().add(lblAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 190, 160));

        lblCatalog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCatalog.setForeground(new java.awt.Color(255, 255, 255));
        lblCatalog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCatalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/catalog1.png"))); // NOI18N
        lblCatalog.setText("Catalog");
        lblCatalog.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCatalog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCatalog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCatalogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCatalogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCatalogMouseExited(evt);
            }
        });
        getContentPane().add(lblCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 190, 160));

        lblRequest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRequest.setForeground(new java.awt.Color(255, 255, 255));
        lblRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/request1.png"))); // NOI18N
        lblRequest.setText("Requests");
        lblRequest.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRequest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRequestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRequestMouseExited(evt);
            }
        });
        getContentPane().add(lblRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 190, 160));

        lblHistory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/history1.png"))); // NOI18N
        lblHistory.setText("History");
        lblHistory.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHistory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHistoryMouseExited(evt);
            }
        });
        getContentPane().add(lblHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 190, 160));

        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 470, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/logoNew.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 620, 300));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/logOut.png"))); // NOI18N
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 60, 40, 50));

        lblUserName.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 250, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/minimize.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 40, 50));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/close2.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 40, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 10));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MAZE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 50));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Home");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 20));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/back.jpg"))); // NOI18N
        lblBackground.setText("jLabel2");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -470, 1681, 1310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCatalogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatalogMouseEntered
        lblCatalog.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view/"
                                + "images/catalog2.png")));
    }//GEN-LAST:event_lblCatalogMouseEntered

    private void lblCatalogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatalogMouseExited
        lblCatalog.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view/"
                                + "images/catalog1.png")));
    }//GEN-LAST:event_lblCatalogMouseExited

    private void lblRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRequestMouseEntered
        lblRequest.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view"
                                + "/images/request2.png")));
    }//GEN-LAST:event_lblRequestMouseEntered

    private void lblRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRequestMouseExited
        lblRequest.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view/"
                                + "images/request1.png")));
    }//GEN-LAST:event_lblRequestMouseExited

    private void lblHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseEntered
        lblHistory.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view/"
                                + "images/history2.png")));
    }//GEN-LAST:event_lblHistoryMouseEntered

    private void lblHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseExited
        lblHistory.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view/"
                                + "images/history1.png")));
    }//GEN-LAST:event_lblHistoryMouseExited

    private void lblAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountMouseEntered
        lblAccount.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view"
                                + "/images/account2.png")));
    }//GEN-LAST:event_lblAccountMouseEntered

    private void lblAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountMouseExited
        lblAccount.setIcon(
                new javax.swing.ImageIcon(getClass().getResource(
                                "/com/ijse/dl/client/view/"
                                + "images/account1.png")));
    }//GEN-LAST:event_lblAccountMouseExited

    private void lblCatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatalogMouseClicked
        if (catalogForm == null) {
            catalogForm = new CatalogForm(this);
        }
        catalogForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCatalogMouseClicked

    private void lblRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRequestMouseClicked
        if (requestForm == null) {
            requestForm = new RequestForm(this);
        }
        requestForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRequestMouseClicked

    private void lblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseClicked
        String userName = null;
        if (historyFrame == null) {
            historyFrame = new HistoryFrame(this);
        }
        historyFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHistoryMouseClicked

    private void lblAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountMouseClicked
        String userName = null;
        if (accountFrame == null) {
            accountFrame = new AccountFrame(this);
        }
        accountFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAccountMouseClicked

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        deleteTemp();
        saveAndExit();
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        saveAndExit();

    }//GEN-LAST:event_formWindowClosing

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        deleteTemp();
        saveAndExit();
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCatalog;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables

    /**
     * Sets current date.
     */
    private void getDate() {
        Date date = new Date();
        SimpleDateFormat simpledateformat
                = (SimpleDateFormat) DateFormat.
                getDateInstance(DateFormat.LONG);
        String newDate = simpledateformat.format(date);
        lblDate.setText(newDate);
    }

    /**
     * Sets current time.
     */
    private void getTime() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date curDate = new Date();
                    SimpleDateFormat dateFormat
                            = new SimpleDateFormat("HH:mm:ss aa");
                    String currentTime = dateFormat.format(curDate);

                    lblClock.setText(currentTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(
                                HomeFrame.this, "Database Error...");
                    }
                }
            }
        }).start();
    }

    private void setLog() throws UnknownHostException {
        DateFormat df = new SimpleDateFormat("HH:mm:ss");
        Date logInDate = new Date();
        String logInTime = df.format(logInDate);

        Date date = new Date();
        SimpleDateFormat simpledateformat
                = (SimpleDateFormat) DateFormat
                .getDateInstance(DateFormat.LONG);
        String curDate = simpledateformat.format(date);

        InetAddress ipAddr = InetAddress.getLocalHost();
        String ipAddrss = ipAddr.getHostAddress();

        log = new Log();
        log.setLogId("0");
        log.setUserId(id);
        log.setLogInTime(logInTime);
        log.setCurDate(curDate);
        log.setIpAddress(ipAddrss);
    }

    private void setFullScreen() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);

        Component component = this;
        component.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        component.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                Rectangle rectangle = getBounds();
                setBounds(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY,
                        rectangle.width, rectangle.height);
            }
        });
    }

    private void saveAndExit() {
        try {
            DateFormat df = new SimpleDateFormat("HH:mm:ss");
            Date logOutDate = new Date();
            String logOutTime = df.format(logOutDate);
            log.setLogOutTime(logOutTime);
            boolean isSaved = new ControllerFactoryImpl()
                    .getLogController().saveLog(log);

            if (isSaved) {
                new LoginFrame().setVisible(true);
                this.dispose();
            }
        } catch (IOException | NotBoundException ex) {
            JOptionPane.showMessageDialog(null, "Server Disconnected", "Oops!",
                    JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }

    private void deleteTemp() {
        File file = new File("./src/tempfiles/");
        String[] fileNames = file.list();
        for (String names : fileNames) {
            System.out.println(names);
            if (!"image".equals(names)) {

                File f = new File("./src/tempfiles/" + names);
                System.out.println(f);
                f.delete();
            }
        }
    }
}
