/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.dl.client.view;

import com.ijse.dl.client.controllerfactoryimpl.ControllerFactoryImpl;
import com.ijse.dl.common.dto.Request;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Randula
 */
public class RequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestPanel
     */
    private ArrayList<Request> list;
    private String idInProccess;
    private Icon icon = new ImageIcon(getClass().getResource(
            "/com/ijse/dl/client/view/images/block.png"));

    public RequestPanel() {
        initComponents();
        loadNameList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMyName = new javax.swing.JLabel();
        txtMyName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        lblDescription1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtAuthor = new javax.swing.JTextField();
        lblAuthor1 = new javax.swing.JLabel();
        lblSubject1 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        txtMediaType = new javax.swing.JTextField();
        lblMediaType1 = new javax.swing.JLabel();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listName = new javax.swing.JList();
        lblTitle = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMyName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblMyName.setForeground(new java.awt.Color(255, 255, 255));
        lblMyName.setText("Member Name");
        add(lblMyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));

        txtMyName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtMyName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        add(txtMyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 360, 30));

        txtName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 360, 30));

        lblName1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Name");
        add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 90, 30));

        lblDescription1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDescription1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription1.setText("Description");
        add(lblDescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 90, 80));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        jScrollPane2.setViewportView(txtDescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 360, 90));

        txtAuthor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtAuthor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 360, 30));

        lblAuthor1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblAuthor1.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthor1.setText("Author");
        add(lblAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, 30));

        lblSubject1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSubject1.setForeground(new java.awt.Color(255, 255, 255));
        lblSubject1.setText("Subject");
        add(lblSubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 90, 30));

        txtSubject.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 360, 30));

        txtMediaType.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtMediaType.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        add(txtMediaType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 360, 30));

        lblMediaType1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblMediaType1.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaType1.setText("Media Type");
        add(lblMediaType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, 30));

        jXTitledPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jXTitledPanel1.setTitle("Requested By");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        listName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listName.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Samadhi", "Nethum", "Amali", "Shanika" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listName);

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        add(jXTitledPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 54, -1, 290));

        lblTitle.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Readers' Requests...");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 224, 26));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/delete1.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setContentAreaFilled(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 102, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/com/ijse/dl/client"
                        + "/view/images/delete2.png")));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/com/ijse/dl/client"
                        + "/view/images/delete1.png")));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void listNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNameMouseClicked
        String selectedName = (String) listName.getSelectedValue();
        setDetails(selectedName);
    }//GEN-LAST:event_listNameMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id = idInProccess;

        deleteRequest(id);

    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JLabel lblAuthor1;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblMediaType1;
    private javax.swing.JLabel lblMyName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblSubject1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList listName;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMediaType;
    private javax.swing.JTextField txtMyName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables

    private void loadNameList() {
        try {
            list = new ControllerFactoryImpl().
                    getRequestController().getAllRequests();
            listName.removeAll();
            if (list.size() > 0) {
                ArrayList<String> nameList = new ArrayList<>();

                for (Request request : list) {
                    nameList.add(request.getMember());
                }
                Collections.sort(nameList);
                listName.setListData(nameList.toArray());
            }
        } catch (IOException | NotBoundException ex) {
            JOptionPane.showMessageDialog(null, "Server Disconnected",
                    "Oops!",
                    JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }

    private void setDetails(String selectedName) {
        try {
            String id = null;
            for (Request request : list) {
                if (selectedName.equalsIgnoreCase(request.getMember())) {
                    id = request.getId();
                    this.idInProccess = id;
                    break;
                }
            }

            Request request
                    = new ControllerFactoryImpl().
                    getRequestController().viewRequest(id);
            if (request != null) {
                txtMyName.setText(request.getMember());
                txtName.setText(request.getBookName());
                txtAuthor.setText(request.getAuthor());
                txtDescription.setText(request.getDescription());
                txtSubject.setText(request.getSubject());
                txtMediaType.setText(request.getMediaType());
            }
        } catch (IOException | NotBoundException ex) {
            JOptionPane.showMessageDialog(null, "Server Disconnected",
                    "Oops!",
                    JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }

    private void deleteRequest(String id) {
        try {
            boolean isDeleted
                    = new ControllerFactoryImpl().
                    getRequestController().deleteRequest(id);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this,
                        "Removed...", "Message", 1);
                txtMyName.setText(null);
                txtName.setText(null);
                txtAuthor.setText(null);
                txtDescription.setText(null);
                txtSubject.setText(null);
                txtMediaType.setText(null);
                loadNameList();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Try Again...", "Message", 1);
            }
        } catch (IOException | NotBoundException ex) {
            JOptionPane.showMessageDialog(null, "Server Disconnected",
                    "Oops!",
                    JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }
}
