/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.dl.client.view;

import com.ijse.dl.client.controllerfactoryimpl.ControllerFactoryImpl;
import com.ijse.dl.client.view.util.Validation;
import com.ijse.dl.common.dto.Membership;
import com.ijse.dl.common.dto.User;
import java.awt.Component;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Randula
 */
public class SignUpStep2Panel extends javax.swing.JPanel {

    /**
     * Creates new form LogInPanel
     */
    private SignUpPanel signUpPanel;
    private LoginFrame loginFrame;

    public SignUpStep2Panel() {
        initComponents();
    }

    SignUpStep2Panel(SignUpPanel signUpPanel, LoginFrame loginFrame) {
        initComponents();
        this.signUpPanel = signUpPanel;
        this.loginFrame = loginFrame;
        txtUserName.requestFocusInWindow();
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        lblName = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        lblFinish = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JTextField();
        lblNic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pssPassword = new javax.swing.JPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        pssPassword1 = new javax.swing.JPasswordField();
        lblBack = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        lblName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Your User Id...");

        txtUserId.setEditable(false);
        txtUserId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(255, 0, 0));
        txtUserId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserId.setText("This Will Fill Automatically");
        txtUserId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtUserId.setOpaque(false);
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        lblFinish.setBackground(new java.awt.Color(29, 78, 217));
        lblFinish.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblFinish.setForeground(new java.awt.Color(255, 255, 255));
        lblFinish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinish.setText("Finish");
        lblFinish.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblFinish.setOpaque(true);
        lblFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinishMouseClicked(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(204, 255, 255));
        txtUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtUserName.setOpaque(false);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });

        lblNic.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNic.setForeground(new java.awt.Color(255, 255, 255));
        lblNic.setText("User Name");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/stepFill.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/dl/client/view/images/stepFill.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Step 2/2");

        lblPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Set your Password");

        pssPassword.setForeground(new java.awt.Color(204, 255, 255));
        pssPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pssPassword.setOpaque(false);
        pssPassword.setPreferredSize(new java.awt.Dimension(72, 23));
        pssPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssPasswordActionPerformed(evt);
            }
        });
        pssPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pssPasswordKeyReleased(evt);
            }
        });

        lblPassword1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Re-enter Password");

        pssPassword1.setForeground(new java.awt.Color(204, 255, 255));
        pssPassword1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pssPassword1.setOpaque(false);
        pssPassword1.setPreferredSize(new java.awt.Dimension(72, 23));
        pssPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pssPassword1KeyReleased(evt);
            }
        });

        lblBack.setBackground(new java.awt.Color(29, 78, 217));
        lblBack.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblBack.setOpaque(true);
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 255, 255));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("We found error in your password!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pssPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNic, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUserId)
                        .addComponent(txtUserName)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pssPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pssPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pssPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        pssPassword.requestFocusInWindow();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void lblFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinishMouseClicked
        String password = String.valueOf(pssPassword.getPassword());
        String passComf = String.valueOf(pssPassword1.getPassword());
        if (password.equals(passComf)) {
            try {
                String genId = saveUserAndMember();
                if (genId != null) {
                    txtUserId.setText(genId);
                    JOptionPane.showMessageDialog(this,
                            "Welcome to Maze | Digital Library..."
                            + "\n" + "Your User Id is : " + genId, "Message",
                            JOptionPane.PLAIN_MESSAGE);
                    new LoginFrame().setVisible(true);
                    loginFrame.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Sign Up Failed...", "Message",
                            JOptionPane.PLAIN_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(SignUpStep2Panel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(SignUpStep2Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            lblError.setVisible(true);
            pssPassword.setText(null);
            pssPassword1.setText(null);
        }
    }//GEN-LAST:event_lblFinishMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        setStepOnePanel();
    }//GEN-LAST:event_lblBackMouseClicked

    private void pssPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssPasswordActionPerformed
        pssPassword1.requestFocusInWindow();
    }//GEN-LAST:event_pssPasswordActionPerformed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
       Validation.name(txtUserName);
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void pssPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pssPasswordKeyReleased
         Validation.removeSemiColen(pssPassword,evt);
    }//GEN-LAST:event_pssPasswordKeyReleased

    private void pssPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pssPassword1KeyReleased
        Validation.removeSemiColen(pssPassword,evt);
    }//GEN-LAST:event_pssPassword1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFinish;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNic;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JPasswordField pssPassword;
    private javax.swing.JPasswordField pssPassword1;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void setStepOnePanel() {
        JPanel panel = loginFrame.panel;

        panel.removeAll();
        signUpPanel.setSize(panel.getSize());
        Component add = panel.add(signUpPanel);
        panel.repaint();
        panel.revalidate();
    }

    private String saveUserAndMember()
            throws IOException, RemoteException, NotBoundException {

        String[] dataList = signUpPanel.getDataList();
        String userName = txtUserName.getText();
        String password = String.valueOf(pssPassword.getPassword());
        String passComf = String.valueOf(pssPassword1.getPassword());

        Date date = new Date();
        SimpleDateFormat simpledateformat
                = (SimpleDateFormat) DateFormat
                .getDateInstance(DateFormat.LONG);
        String newDate = simpledateformat.format(date);

        User user
                = new User("0", dataList[0], dataList[1],
                        dataList[2], dataList[3],"User");
        Membership membership
                = new Membership("0", userName,
                        password, newDate,"User");
        String genId
                = new ControllerFactoryImpl()
                .getMemberController().addAsMember(membership, user);

        return genId;
    }
}
